services:
  _defaults:
    public: true

  marsaldev.module.protectimages.form.type.protect_images_configuration:
    class: 'Marsaldev\Module\MsdProtectImages\Form\ProtectImagesConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  marsaldev.module.protectimages.form.protect_images_configuration_data_configuration:
    class: 'Marsaldev\Module\MsdProtectImages\Form\ProtectImagesConfigurationDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@translator'
      - '@prestashop.core.cache.clearer.cache_clearer_chain'

  marsaldev.module.protectimages.form.protect_images_form_data_provider:
    class: 'Marsaldev\Module\MsdProtectImages\Form\ProtectImagesConfigurationDataProvider'
    arguments:
      - '@marsaldev.module.protectimages.form.protect_images_configuration_data_configuration'

  marsaldev.module.protectimages.form.protect_images_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@marsaldev.module.protectimages.form.protect_images_form_data_provider'
      - 'Marsaldev\Module\MsdProtectImages\Form\ProtectImagesConfigurationFormType'
      - 'MsdProtectImages'